### ISSUE TITLE
Unable to turn strip off when running certain animations on version Apr 2, 2017

### ISSUE THREAD

**Issue by bfqrst** [bruhautomation/ESP-MQTT-JSON-Digital-LEDs#10]
Hi there,

Here is another issue I encountered:

When you are on `cyclon rainbow` or `lighning`, turning the strip off from the HA gui has no effect. The HA gui updates to `off` but the animation on the strip keeps going. One has to hit `on` again, change the animation to something other than `cyclon rainbow` or `lightning` and then switch the strip off. In this case the strip goes dark.

Cheers
Ralph

**Comment by bruhautomation** [comment]
Thanks much for catching this! I was seeing similar things in my setup. I just pushed an update that should resolve it. Cheers!
