### ISSUE TITLE
Does this support 5050 rgb strips or only the WS2812 that are addressable ?

### ISSUE THREAD

**Issue by donnib** [bruhautomation/ESP-MQTT-JSON-Digital-LEDs#38]
Hi,
Does this support 5050 rgb strips or only the WS2812 that are addressable ?

donnib

**Comment by drschnalli** [comment]
Only addressable LED Strips.

**Comment by Makr91** [comment]
On his Youtube page he links these:
https://www.youtube.com/watch?v=9KI36GTgwuQ&t=215s

https://www.amazon.com/gp/product/B01CNL6MNM/ref=as_li_ss_tl?tag=brau01-20&ie=UTF8&psc=1&linkCode=ll1&linkId=b171287418103cdf0b7b5029b77e8f6e

These appear to be both 5050SMD and Addressable, however I am also having an issue getting the Addressing to work.
