### ISSUE TITLE
Fire effect doesnt work?

### ISSUE THREAD

**Issue by KodiMkd** [bruhautomation/ESP-MQTT-JSON-Digital-LEDs#50]
Hi i just noticed th at fire effect doesnt work..i mean the led lights up but its only white color plain. No red or any other color with effect
Anyone else having same issue with fire effect?

**Comment by timmo001** [comment]
The fire is a yellow-like color for me. It could do with adding a bit of variance with more reds and oranges etc. I will try to edit the code and see if I can get this to work for me, then send a pull request

**Comment by edif30** [comment]
Yes.  But mine just lights up once and then stays out.  It's like it "starts" but never continues.
