### ISSUE TITLE
ws2812b led colors is incorrect

### ISSUE THREAD

**Issue by 893399065** [bruhautomation/ESP-MQTT-JSON-Digital-LEDs#72]
I use the ws2812b with esp8266. I find that when I set color  green but it shows blue, and when I set color blue it shows green. Finally, I found out the code should change '#define COLOR_ORDER BRG' to '#define COLOR_ORDER GRB'.

**Comment by pacobyte** [comment]
The value for that `#define` depends on the particular LED strip that is being used. The same applies to the other `#define`s for the **FastLED Definitions**. In other words, this isn't an issue that needs to be fixed.

That being said, I'm glad you got it figured out.
