### ISSUE TITLE
Node mcu crashing after few minutes after selecting effect

### ISSUE THREAD

**Issue by xBiohazardx** [bruhautomation/ESP-MQTT-JSON-Digital-LEDs#77]
Hello there,
This code is pretty awsome, but as mentioned before my node mcu crashes after a few minutes. After crashing it restarts and is available in the network (pingable), but doesn't react to the mqtt messages. After pressing the reset button everything works fine for about 5 minutes again. Thanks for your help.

**Comment by pcdiks** [comment]
Happens to me too, it works fine for a couple of minutes and then it crashes and becomes not responsive. I have to powercycle it to come back online.

**Comment by ddtmax** [comment]
unfortunately it happens to me too, after 2 minutes with some effects

**Comment by nickboucher** [comment]
This happens to me too -- I have a suspicion that the culprit is how FastLED interacts with the architecture of the NodeMCU as discussed in #60. I will be testing in a week and will report back if any of the proposed fixes in that thread work. 

Also, for reference, I believe the issue being discussed in #73 is the same as this thread.

**Comment by xBiohazardx** [comment]
It seems to be stable for me now. In the Arduino IDE are two versions of the NodeMCU. I changed from version 1.0 to 0.9 and I think this fixed it for me. Leave a command if it also helped you please.

**Comment by xBiohazardx** [comment]
It seems that changing the line "FastLed.delay(1000 / TransitionTime);" in function show Leds, to just "delay(1000 / TansitionTime);" fixed this issue for me.

**Comment by bacumings** [comment]
Curious how many total LEDs you guys have connected? I am having similar issues and just discovered that there are several places in the code that use 8-bit functions on the NUM_LEDS variable. I have three connected strips with a total of 272 addressable LEDs and am wondering if this isn't causing issues.

**Comment by xBiohazardx** [comment]
I have got 60 of them connected. But my issue on two of my strips i got a loose connection. (I am a very good engineer xD) sry for the late answer I am closing the issue if you still need help please open another one.
