### ISSUE TITLE
External Power Issue

### ISSUE THREAD

**Issue by JaiSpicer** [bruhautomation/ESP-MQTT-JSON-Digital-LEDs#83]
HI guys,

I'm having an issue when trying to run my LED's with an external 5V power supply it appears to be the level shiftier. It works with the ESO8266 plugged via USB however when using external power it doesn't however if i take out the level shift it works again. Does anyone have any idea why this would be and if they could help?

This is the shiftier I'm using
https://www.ebay.com.au/itm/3-3V-5V-2-Channel-Logic-Level-Converter-TTL-Bi-Directional-Shifter-Module-/232714255844?hash=item362ed9bde4

**Comment by euf0ria** [comment]
Have you tried the other channel on the levelshifter? I had a a shifter recently that did not work on one channel. (or maybe i tried to use it in a faulty manner).
