### ISSUE TITLE
monitor serial not showing anything

### ISSUE THREAD

**Issue by arissaraiva** [bruhautomation/ESP-MQTT-JSON-Digital-LEDs#84]
Hello I did downloaded the sketch it showed until the 100% after this I went to monitor serial and it´s not showing anything. Did a miss anything?

**Comment by arissaraiva** [comment]
I adjust the velocity to 115200 and now it´s only showing dots.

**Comment by arissaraiva** [comment]
just adding that my nodemcu shows in my client list but when I try to ping him it does not respond

**Comment by federom** [comment]
Check your Wifi settings.. It happens the same to me, the password was not correct and i experienced the same situation

**Comment by arissaraiva** [comment]
thanks for the reply, indeed I was missing some capital letters on my username, but I adjusted everything and now I can see on my client list and it´s receiving my pings, also I setup my mosquitto in hass.io and in my logs it apears that nodmcu is conecting, but still, nothing apears on my serial monitor, I think it´s a problem with IDE

**Comment by federom** [comment]
Were you able to make the lights work ?

**Comment by arissaraiva** [comment]
I´m not with the whole package of things still waiting for the wires and digital stripes, so I´ll have to wait to post if everything is running well

**Comment by arissaraiva** [comment]
Flashed again now its working

**Comment by federom** [comment]
Great !
