### ISSUE TITLE
how does the wiring goes without level shifter?

### ISSUE THREAD

**Issue by arissaraiva** [bruhautomation/ESP-MQTT-JSON-Digital-LEDs#85]
Guys as per my understanding it´s possible not to use the level shifter, if true how does the wiring goes?esp8266 supports 5v?

**Comment by federom** [comment]
I think you cant if the Output pin has a 3.3 volts reference like NodeMCU

**Comment by arissaraiva** [comment]
it´s that bruh said in the video, or a misunderstood that it wasn´t necessary
